// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCw01-Pe3Nor-vHEjhPWiqnSh_q4w_5SA',
    appId: '1:609456568928:web:658c9fa676a219d0292105',
    messagingSenderId: '609456568928',
    projectId: 'bookly-app-68c4e',
    authDomain: 'bookly-app-68c4e.firebaseapp.com',
    storageBucket: 'bookly-app-68c4e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWWiclQOQZqlfgfhSSNJRaxjK_DlQ6ixQ',
    appId: '1:609456568928:android:be2ed96af2a2bc14292105',
    messagingSenderId: '609456568928',
    projectId: 'bookly-app-68c4e',
    storageBucket: 'bookly-app-68c4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCavEJRbHbA2GrHXkyzDTvWbdwlpv3Tusg',
    appId: '1:609456568928:ios:52097dd0eb770cb5292105',
    messagingSenderId: '609456568928',
    projectId: 'bookly-app-68c4e',
    storageBucket: 'bookly-app-68c4e.firebasestorage.app',
    iosBundleId: 'com.example.booklyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCavEJRbHbA2GrHXkyzDTvWbdwlpv3Tusg',
    appId: '1:609456568928:ios:52097dd0eb770cb5292105',
    messagingSenderId: '609456568928',
    projectId: 'bookly-app-68c4e',
    storageBucket: 'bookly-app-68c4e.firebasestorage.app',
    iosBundleId: 'com.example.booklyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCw01-Pe3Nor-vHEjhPWiqnSh_q4w_5SA',
    appId: '1:609456568928:web:704769918f1115be292105',
    messagingSenderId: '609456568928',
    projectId: 'bookly-app-68c4e',
    authDomain: 'bookly-app-68c4e.firebaseapp.com',
    storageBucket: 'bookly-app-68c4e.firebasestorage.app',
  );
}
